version: '3.5'

services:
  medium-server:
    build: Server/
    restart: always
    ports: 
      - "7000:80"
    depends_on: 
      - medium-db
    networks: 
      - medium-net
  
  medium-db: 
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: medium-db
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Master2020#
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes: 
      - medium-db-sql:/var/opt/mssql
    networks: 
      - medium-net
    
volumes:
  medium-db-sql:

networks:
  medium-net:
    name: medium-net