name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore
      run: dotnet restore .//Server//
    - name: Build
      run: dotnet build .//Server// --configuration Release --no-restore
    - name: Unit Test
      run: dotnet test .//Server//test//Medium.UnitTest// --no-restore --verbosity normal
    - name: Integration Test
      run: dotnet test .//Server//test//Medium.IntegrationTest// --no-restore --verbosity normal
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
